frappe.pages['huf-chat'].on_page_load = function(wrapper) {
  const page = frappe.ui.make_app_page({ parent: wrapper, title: 'Trilogy Ai Chat', single_column: true });
  const $root = $(page.body).addClass('huf-full-chat-page');
  $root.html(`<div class="huf-full-chat" dir="rtl"><aside class="huf-full-sidebar"><button class="btn btn-primary btn-sm" data-new>محادثة جديدة</button><div data-sessions></div></aside><section class="huf-full-main"><div class="huf-full-list" data-list></div><div class="huf-full-prompts"></div><footer><textarea rows="2" placeholder="اكتب طلبك هنا..."></textarea><button class="btn btn-primary" data-send>إرسال</button></footer></section><aside class="huf-full-debug" hidden><pre data-debug></pre></aside></div>`);
  $('<style>').text(`.huf-full-chat{display:grid;grid-template-columns:260px 1fr;gap:12px;height:calc(100vh - 150px)}.huf-full-sidebar,.huf-full-main,.huf-full-debug{border:1px solid #dbe3ef;border-radius:10px;background:#fff;overflow:hidden}.huf-full-sidebar{padding:10px}.huf-full-list{height:calc(100% - 76px);overflow:auto;padding:16px;background:#f6f8fc}.huf-full-main footer{display:flex;gap:8px;padding:10px;border-top:1px solid #dbe3ef}.huf-full-main textarea{flex:1;border:1px solid #dbe3ef;border-radius:8px;padding:9px}.huf-msg{margin:8px 0;display:flex}.huf-msg.user{justify-content:flex-start}.huf-msg.assistant{justify-content:flex-end}.huf-bubble{max-width:78%;padding:10px 12px;border:1px solid #dbe3ef;border-radius:10px;background:#fff;line-height:1.7}.huf-msg.user .huf-bubble{background:#eaf2ff}.huf-session{display:block;width:100%;margin:8px 0;text-align:right}.huf-full-prompts{display:flex;gap:7px;flex-wrap:wrap;padding:10px;border-top:1px solid #dbe3ef}.huf-full-prompts button{border:1px solid #dbe3ef;border-radius:8px;background:#fff;padding:7px 10px}.huf-full-debug{padding:10px}@media(max-width:900px){.huf-full-chat{grid-template-columns:1fr}.huf-full-sidebar{display:none}}`).appendTo(document.head);
  let sessionId = null;
  const prompts = ['اعرض مبيعات هذا الشهر', 'ما الفواتير المتأخرة؟', 'لخص حالة المخزون', 'اقترح تحسينات على التدفق النقدي', 'اعطني تقريراً تنفيذياً مختصراً'];
  const esc = v => String(v || '').replace(/[&<>"']/g, s => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
  const api = (m,args) => new Promise((resolve,reject)=>frappe.call({method:`huf.api.chat.${m}`,args,callback:r=>resolve(r.message),error:reject}));
  function add(role,text){$root.find('[data-list]').append(`<div class="huf-msg ${role}"><div class="huf-bubble">${esc(text).replace(/\n/g,'<br>')}</div></div>`).scrollTop(999999)}
  async function refreshSessions(){let r={sessions:[]}; try { r=await api('get_sessions',{limit:30}); } catch(e) { frappe.msgprint(__('Unable to load Trilogy Ai sessions')); console.error(e); return; }$root.find('[data-sessions]').html((r.sessions||[]).map(s=>`<button class="btn btn-default btn-sm huf-session" data-session="${s.name}">${esc(s.title||s.name)}</button>`).join(''));$root.find('[data-session]').on('click',async function(){sessionId=this.dataset.session;const m=await api('get_messages',{session_id:sessionId});$root.find('[data-list]').empty();(m.messages||[]).forEach(x=>add(x.role==='agent'?'assistant':x.role,x.content));});}
  async function send(text){if(!text.trim())return;add('user',text);$root.find('textarea').val('');try{const res=await api('send_message',{message:text,session_id:sessionId});sessionId=res.session_id;add('assistant',res.content||'لم يصل رد واضح.');refreshSessions();}catch(e){add('assistant','تعذر تنفيذ الطلب. راجع الصلاحيات أو إعدادات النموذج.');console.error(e);}}
  $root.find('.huf-full-prompts').html(prompts.map(p=>`<button>${p}</button>`).join('')).find('button').on('click',function(){send($(this).text())});
  $root.find('[data-send]').on('click',()=>send($root.find('textarea').val()));
  $root.find('textarea').on('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(e.target.value)}});
  $root.find('[data-new]').on('click',async()=>{const r=await api('new_session',{});sessionId=r.session_id;$root.find('[data-list]').empty();refreshSessions();});
  refreshSessions();
};
